// PostToolUse contract alert: when an edit touches a file matching config.contracts.paths, record which exported symbols it
// now declares (journal event, published by the worker) and tell Claude which teammates work under the same top-level area
// so it can mention the change to them. Symbols come from this machine's own file; teammate fields are validated identifiers.
import fs from 'node:fs';
import path from 'node:path';
import { readConfig, matchesAny } from '../core/config.mjs';
import { LIMITS } from '../core/schema.mjs';
import { nowMs, readIdentity, snapshotFromCtx, teammates, claimActive, presenceAgeMs, tierOf, repoRelativePath, MS } from './common.mjs';
import { editedPath } from './collision.mjs';
import { appendJournal } from './journal-write.mjs';
import { extractSymbols } from './symbols.mjs';

const MAX_READ = 256 * 1024;
const MAX_TEAMMATES = 8;

function readHead(file) {
  let fd = null;
  try {
    fd = fs.openSync(file, 'r');
    const size = Math.min(fs.fstatSync(fd).size, MAX_READ);
    const buf = Buffer.alloc(size);
    fs.readSync(fd, buf, 0, size, 0);
    return buf.toString('utf8');
  } catch { return ''; } finally { if (fd !== null) { try { fs.closeSync(fd); } catch { /* closed */ } } }
}

export function topLevelArea(rel) { const i = rel.indexOf('/'); return i === -1 ? '' : rel.slice(0, i); }

/** Teammates whose claims, recent edits or declared area fall under `area` (a top-level directory). Exported for tests. */
export function teammatesInArea(snapshot, identity, area, now) {
  const rows = [];
  const under = (p) => p && (area === '' ? !p.includes('/') : p === area || p.startsWith(area + '/'));
  for (const w of teammates(snapshot, identity)) {
    if (tierOf(presenceAgeMs(w, now)) === 'gone') continue;
    const reasons = [];
    const claims = (w.claims || []).filter((c) => c.path && claimActive(c, w, now) && under(c.path)).map((c) => c.path);
    if (claims.length) reasons.push(`claims ${claims.slice(0, 3).join(', ')}`);
    const edits = (w.edits || []).filter((e) => under(e.path) && now - Date.parse(e.at) < MS.day).map((e) => e.path);
    if (edits.length) reasons.push(`edited ${[...new Set(edits)].slice(0, 3).join(', ')}`);
    if (w.presence && under(w.presence.area)) reasons.push(`area ${w.presence.area}`);
    if (reasons.length) rows.push({ handle: w.handle, branch: w.presence && w.presence.branch, verified: w.verified, reasons });
  }
  return rows.slice(0, MAX_TEAMMATES);
}

export async function contractAlert(ctx, toolInput) {
  if (!ctx || !ctx.loc || ctx.muted) return null;
  const now = nowMs(ctx);
  const filePath = editedPath(toolInput);
  const rel = repoRelativePath(ctx.loc, ctx.cwd, filePath);
  if (!rel) return null;
  const config = readConfig(ctx.loc.workTree);
  if (!matchesAny(rel, config.contracts.paths)) return null;
  const abs = path.isAbsolute(filePath) ? filePath : path.join(ctx.cwd || ctx.loc.workTree, filePath);
  const symbols = extractSymbols(rel, readHead(abs));
  appendJournal(ctx.loc.checkoutDir, { type: 'contract-change', path: rel, symbols }, { sid: ctx.sessionId });

  const identity = readIdentity(ctx.loc.checkoutDir);
  const snapshot = snapshotFromCtx(ctx);
  if (!identity || !snapshot) return null;
  const area = topLevelArea(rel);
  const rows = teammatesInArea(snapshot, identity, area, now);
  if (!rows.length) return null;
  const who = rows.map((r) => `${r.handle}${r.branch ? ` (branch ${r.branch})` : ''}: ${r.reasons.join('; ')}${r.verified === 'yes' ? '' : ` [verified=${r.verified}]`}`);
  const head = `Synchrobuilder: ${rel} is a contract file${symbols.length ? ` (now exports ${symbols.join(', ')})` : ''}. Teammates working under ${area ? `${area}/` : 'the repository root'} according to the local sync cache: ${who.join(' | ')}. Consider telling them about the change with /synchrobuilder:notify <handle> <message>. This note is generated by the plugin from validated fields; teammate state is their claim, not verified fact.`;
  return head.length > LIMITS.alertChars ? head.slice(0, LIMITS.alertChars - 2) + ' ~' : head;
}
